name: analog

services:
  postgres:
    image: postgres:18.1
    restart: always
    container_name: analog-db
    environment:
      POSTGRES_USER: analog
      POSTGRES_PASSWORD: analog
      POSTGRES_DB: analog
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./packages/db/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

volumes:
  pgdata: