CREATE TABLE "app"."catalog_item_isbn" (
	"isbn" text PRIMARY KEY NOT NULL,
	"catalog_item_id" uuid NOT NULL,
	"main" boolean DEFAULT false NOT NULL,
	"title" text,
	"cover_url" text,
	"publisher" text,
	"language" text,
	"format" text,
	"pending" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."collection_item_isbn" (
	"collection_item_id" uuid NOT NULL,
	"isbn" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "collection_item_isbn_collection_item_id_isbn_pk" PRIMARY KEY("collection_item_id","isbn")
);
--> statement-breakpoint
ALTER TABLE "app"."series" ADD COLUMN "created_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "app"."catalog_item_isbn" ADD CONSTRAINT "catalog_item_isbn_catalog_item_id_catalog_item_id_fk" FOREIGN KEY ("catalog_item_id") REFERENCES "app"."catalog_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."collection_item_isbn" ADD CONSTRAINT "collection_item_isbn_collection_item_id_collection_item_id_fk" FOREIGN KEY ("collection_item_id") REFERENCES "app"."collection_item"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."collection_item_isbn" ADD CONSTRAINT "collection_item_isbn_isbn_catalog_item_isbn_isbn_fk" FOREIGN KEY ("isbn") REFERENCES "app"."catalog_item_isbn"("isbn") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "catalog_item_isbn_catalog_item_id_idx" ON "app"."catalog_item_isbn" USING btree ("catalog_item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "catalog_item_isbn_main_idx" ON "app"."catalog_item_isbn" USING btree ("catalog_item_id") WHERE "app"."catalog_item_isbn"."main";--> statement-breakpoint
CREATE INDEX "collection_item_isbn_isbn_idx" ON "app"."collection_item_isbn" USING btree ("isbn");--> statement-breakpoint
ALTER TABLE "app"."series" ADD CONSTRAINT "series_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "app"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."series" DROP COLUMN "language";--> statement-breakpoint
-- Every book's own ISBN goes in the new table as its main ISBN, before the
-- barcode column it came from is dropped.
-- Its language comes from the first language name in the book's metadata.
INSERT INTO "app"."catalog_item_isbn" ("isbn", "catalog_item_id", "main", "title", "cover_url", "publisher", "language", "format")
SELECT
    "c"."barcode",
    "c"."id",
    true,
    "c"."title",
    "c"."cover_url",
    "c"."metadata" -> 'publishers' ->> 0,
    "l"."code",
    "c"."metadata" ->> 'physicalFormat'
FROM "app"."catalog_item" AS "c"
LEFT JOIN (
    VALUES
        ('Afar', 'aa'),
        ('Abkhazian', 'ab'),
        ('Avestan', 'ae'),
        ('Afrikaans', 'af'),
        ('Akan', 'ak'),
        ('Amharic', 'am'),
        ('Aragonese', 'an'),
        ('Arabic', 'ar'),
        ('Assamese', 'as'),
        ('Avaric', 'av'),
        ('Aymara', 'ay'),
        ('Azerbaijani', 'az'),
        ('Bashkir', 'ba'),
        ('Belarusian', 'be'),
        ('Bulgarian', 'bg'),
        ('Bhojpuri', 'bh'),
        ('Bislama', 'bi'),
        ('Bambara', 'bm'),
        ('Bangla', 'bn'),
        ('Tibetan', 'bo'),
        ('Breton', 'br'),
        ('Bosnian', 'bs'),
        ('Catalan', 'ca'),
        ('Chechen', 'ce'),
        ('Chamorro', 'ch'),
        ('Corsican', 'co'),
        ('Cree', 'cr'),
        ('Czech', 'cs'),
        ('Church Slavic', 'cu'),
        ('Chuvash', 'cv'),
        ('Welsh', 'cy'),
        ('Danish', 'da'),
        ('German', 'de'),
        ('Divehi', 'dv'),
        ('Dzongkha', 'dz'),
        ('Ewe', 'ee'),
        ('Greek', 'el'),
        ('English', 'en'),
        ('Esperanto', 'eo'),
        ('Spanish', 'es'),
        ('Estonian', 'et'),
        ('Basque', 'eu'),
        ('Persian', 'fa'),
        ('Fula', 'ff'),
        ('Finnish', 'fi'),
        ('Fijian', 'fj'),
        ('Faroese', 'fo'),
        ('French', 'fr'),
        ('Western Frisian', 'fy'),
        ('Irish', 'ga'),
        ('Scottish Gaelic', 'gd'),
        ('Galician', 'gl'),
        ('Guarani', 'gn'),
        ('Gujarati', 'gu'),
        ('Manx', 'gv'),
        ('Hausa', 'ha'),
        ('Hebrew', 'he'),
        ('Hindi', 'hi'),
        ('Hiri Motu', 'ho'),
        ('Croatian', 'hr'),
        ('Haitian Creole', 'ht'),
        ('Hungarian', 'hu'),
        ('Armenian', 'hy'),
        ('Herero', 'hz'),
        ('Interlingua', 'ia'),
        ('Indonesian', 'id'),
        ('Interlingue', 'ie'),
        ('Igbo', 'ig'),
        ('Sichuan Yi', 'ii'),
        ('Inupiaq', 'ik'),
        ('Ido', 'io'),
        ('Icelandic', 'is'),
        ('Italian', 'it'),
        ('Inuktitut', 'iu'),
        ('Japanese', 'ja'),
        ('Yiddish', 'ji'),
        ('Javanese', 'jv'),
        ('Georgian', 'ka'),
        ('Kongo', 'kg'),
        ('Kikuyu', 'ki'),
        ('Kuanyama', 'kj'),
        ('Kazakh', 'kk'),
        ('Kalaallisut', 'kl'),
        ('Khmer', 'km'),
        ('Kannada', 'kn'),
        ('Korean', 'ko'),
        ('Kanuri', 'kr'),
        ('Kashmiri', 'ks'),
        ('Kurdish', 'ku'),
        ('Komi', 'kv'),
        ('Cornish', 'kw'),
        ('Kyrgyz', 'ky'),
        ('Latin', 'la'),
        ('Luxembourgish', 'lb'),
        ('Ganda', 'lg'),
        ('Limburgish', 'li'),
        ('Lingala', 'ln'),
        ('Lao', 'lo'),
        ('Lithuanian', 'lt'),
        ('Luba-Katanga', 'lu'),
        ('Latvian', 'lv'),
        ('Malagasy', 'mg'),
        ('Marshallese', 'mh'),
        ('Māori', 'mi'),
        ('Macedonian', 'mk'),
        ('Malayalam', 'ml'),
        ('Mongolian', 'mn'),
        ('Romanian', 'mo'),
        ('Marathi', 'mr'),
        ('Malay', 'ms'),
        ('Maltese', 'mt'),
        ('Burmese', 'my'),
        ('Nauru', 'na'),
        ('Norwegian Bokmål', 'nb'),
        ('North Ndebele', 'nd'),
        ('Nepali', 'ne'),
        ('Ndonga', 'ng'),
        ('Dutch', 'nl'),
        ('Norwegian Nynorsk', 'nn'),
        ('Norwegian', 'no'),
        ('South Ndebele', 'nr'),
        ('Navajo', 'nv'),
        ('Nyanja', 'ny'),
        ('Occitan', 'oc'),
        ('Ojibwa', 'oj'),
        ('Oromo', 'om'),
        ('Odia', 'or'),
        ('Ossetic', 'os'),
        ('Punjabi', 'pa'),
        ('Pali', 'pi'),
        ('Polish', 'pl'),
        ('Pashto', 'ps'),
        ('Portuguese', 'pt'),
        ('Quechua', 'qu'),
        ('Romansh', 'rm'),
        ('Rundi', 'rn'),
        ('Russian', 'ru'),
        ('Kinyarwanda', 'rw'),
        ('Sanskrit', 'sa'),
        ('Sardinian', 'sc'),
        ('Sindhi', 'sd'),
        ('Northern Sami', 'se'),
        ('Sango', 'sg'),
        ('Serbian (Latin)', 'sh'),
        ('Sinhala', 'si'),
        ('Slovak', 'sk'),
        ('Slovenian', 'sl'),
        ('Samoan', 'sm'),
        ('Shona', 'sn'),
        ('Somali', 'so'),
        ('Albanian', 'sq'),
        ('Serbian', 'sr'),
        ('Swati', 'ss'),
        ('Southern Sotho', 'st'),
        ('Sundanese', 'su'),
        ('Swedish', 'sv'),
        ('Swahili', 'sw'),
        ('Tamil', 'ta'),
        ('Telugu', 'te'),
        ('Tajik', 'tg'),
        ('Thai', 'th'),
        ('Tigrinya', 'ti'),
        ('Turkmen', 'tk'),
        ('Filipino', 'tl'),
        ('Tswana', 'tn'),
        ('Tongan', 'to'),
        ('Turkish', 'tr'),
        ('Tsonga', 'ts'),
        ('Tatar', 'tt'),
        ('Tahitian', 'ty'),
        ('Uyghur', 'ug'),
        ('Ukrainian', 'uk'),
        ('Urdu', 'ur'),
        ('Uzbek', 'uz'),
        ('Venda', 've'),
        ('Vietnamese', 'vi'),
        ('Volapük', 'vo'),
        ('Walloon', 'wa'),
        ('Wolof', 'wo'),
        ('Xhosa', 'xh'),
        ('Yoruba', 'yo'),
        ('Zhuang', 'za'),
        ('Chinese', 'zh'),
        ('Zulu', 'zu')
) AS "l"("name", "code") ON "l"."name" = "c"."metadata" -> 'languages' ->> 0
WHERE "c"."format" = 'book' AND "c"."barcode" IS NOT NULL;--> statement-breakpoint
-- A book in a collection was added by scanning its ISBN, so it owns that edition.
INSERT INTO "app"."collection_item_isbn" ("collection_item_id", "isbn")
SELECT "ci"."id", "c"."barcode"
FROM "app"."collection_item" AS "ci"
JOIN "app"."catalog_item" AS "c" ON "c"."id" = "ci"."catalog_item_id"
WHERE "c"."format" = 'book' AND "c"."barcode" IS NOT NULL;--> statement-breakpoint
-- Every ISBN now lives in catalog_item_isbn.
ALTER TABLE "app"."catalog_item" DROP CONSTRAINT "catalog_item_barcode_unique";--> statement-breakpoint
ALTER TABLE "app"."catalog_item" DROP COLUMN "barcode";
